# Generated by Django 2.0 on 2018-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialgroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='dam_asset',
            field=models.URLField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
