# Generated by Django 2.0 on 2018-09-05 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0003_auto_20180905_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrevision',
            name='material_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='material_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsecmh.MaterialRevision'),
        ),
    ]
