# Generated by Django 2.0 on 2018-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0004_auto_20180905_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrevision',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('MODELS_LOADING', 'Manifest editing'), ('MODELS_LOADING', 'Models loading'), ('VALIDATING', 'Validating'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='NEW', max_length=256),
        ),
    ]
