# Generated by Django 2.0 on 2018-09-24 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0005_materialrevision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrevision',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
