# Generated by Django 2.0 on 2018-09-24 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0006_materialrevision_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('resource_type', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('temporary', models.BooleanField(default=False, verbose_name='Temporary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='dam_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsecmh.DamAsset'),
        ),
    ]
