# Generated by Django 2.0 on 2018-09-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0007_auto_20180924_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialasset',
            name='dam_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elsecmh.DamAsset'),
        ),
    ]
