# Generated by Django 2.0 on 2018-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0008_auto_20180924_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialasset',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
