# Generated by Django 2.0 on 2018-09-26 17:08

from django.db import migrations, models
import elsecmh.models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0009_auto_20180926_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialasset',
            name='file',
            field=models.FileField(null=True, upload_to=elsecmh.models.generate_file_name),
        ),
    ]
