# Generated by Django 2.0 on 2018-09-28 14:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0010_auto_20180926_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrevision',
            name='material_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
