# Generated by Django 2.0 on 2018-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0011_auto_20180928_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='active_revision',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_group',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='dam_asset',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='material_revision',
        ),
        migrations.RemoveField(
            model_name='materialrevision',
            name='material',
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
        migrations.DeleteModel(
            name='DamAsset',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialAsset',
        ),
        migrations.DeleteModel(
            name='MaterialGroup',
        ),
        migrations.DeleteModel(
            name='MaterialRevision',
        ),
    ]
