# Generated by Django 2.0 on 2018-11-20 16:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elsecmh', '0012_auto_20181119_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialAsset',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('dam_uuid', models.UUIDField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=255, null=True)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, verbose_name='About')),
                ('temporary', models.BooleanField(default=False, verbose_name='Temporary')),
                ('meta_info', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialRevision',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('material_info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('MODELS_LOADING', 'Models loading'), ('MODELS_LOADED', 'Models loaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='NEW', max_length=256)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='elsecmh.Material')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='materialasset',
            name='material_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='elsecmh.MaterialRevision'),
        ),
        migrations.AddField(
            model_name='material',
            name='active_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='elsecmh.MaterialRevision'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elsecmh.MaterialGroup'),
        ),
    ]
