# Generated by Django 2.0 on 2018-12-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0013_auto_20181120_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialasset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='temporary',
        ),
    ]
