# Generated by Django 2.0 on 2018-12-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0014_auto_20181207_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='elsecmh.MaterialGroup'),
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='material_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='elsecmh.MaterialRevision'),
        ),
    ]
