# Generated by Django 2.0 on 2019-01-10 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0015_auto_20181213_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMetaData',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('AXF_RAW_DATA', 'AxF raw data'), ('AXF_META_DATA', 'AxF meta data')], default='AXF_META_DATA', max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(default='')),
                ('material_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='elsecmh.MaterialRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('AXF_ASSET', 'AxF asset')], max_length=255, null=True),
        ),
    ]
