# Generated by Django 2.0 on 2019-01-21 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0016_auto_20190110_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialImplementation',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('name', models.CharField(max_length=255)),
                ('material_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementations', to='elsecmh.MaterialRevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialImplementationAsset',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('dam_uuid', models.UUIDField(null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(max_length=255, null=True)),
                ('brand_id', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('resource_type', models.CharField(max_length=255, null=True)),
                ('meta_info', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset')], max_length=255, null=True)),
                ('material_implementation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='elsecmh.MaterialImplementation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('AXF_ASSET', 'AxF asset')], max_length=255, null=True),
        ),
    ]
