# Generated by Django 2.0 on 2019-01-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0017_auto_20190121_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialimplementation',
            unique_together={('name', 'material_revision', 'deleted')},
        ),
    ]
