# Generated by Django 2.0 on 2019-01-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0019_change_mat_rev_asset_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='materialimplementationasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('B4W_ASSET', 'B4W asset'), ('AXF_ASSET', 'AxF asset')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'deleted')},
        ),
    ]
