# Generated by Django 2.0 on 2019-01-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0019_change_mat_rev_asset_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('AXF_ASSET', 'AxF asset'), ('ENVIRONMENT_ASSET', 'Environment asset'), ('SETTINGS_ASSET', 'Settings asset')], max_length=255, null=True),
        ),
    ]
