# Generated by Django 2.0 on 2019-02-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0021_change_mat_imp_asset_types'),
        ('elsecmh', '0020_auto_20190128_0739'),
    ]

    operations = [
    ]
