# Generated by Django 2.0 on 2019-02-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0022_merge_20190225_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimplementationasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('PREVIEW_ASSET', 'Preview asset'), ('AXF_ASSET', 'AxF asset'), ('JSON_ASSET', 'JSON asset'), ('HTML_ASSET', 'HTML asset')], max_length=255, null=True),
        ),
    ]
