# Generated by Django 2.0 on 2019-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0023_auto_20190225_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrevision',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published')], default='NEW', max_length=256),
        ),
    ]
