# Generated by Django 2.1.7 on 2019-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0026_materialrevision_default_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('ENVIRONMENT_ASSET', 'Environment asset'), ('SETTINGS_ASSET', 'Settings asset'), ('AXF_ASSET', 'AxF asset'), ('PREVIEW_ASSET', 'Preview asset')], max_length=255, null=True),
        ),
    ]
