# Generated by Django 2.1.7 on 2019-04-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0028_auto_20190422_1537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'brand', 'deleted')},
        ),
    ]
