# Generated by Django 2.1.7 on 2019-05-15 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0029_auto_20190430_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialasset',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='materialimplementationasset',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='materialasset',
            name='asset_type',
            field=models.CharField(choices=[('MODEL_ASSET', 'Model asset'), ('ENVIRONMENT_ASSET', 'Environment asset'), ('SETTINGS_ASSET', 'Settings asset'), ('AXF_ASSET', 'AxF asset'), ('U3M_ASSET', 'U3M asset'), ('PREVIEW_ASSET', 'Preview asset'), ('TEXTURE_ASSET', 'Texture asset')], max_length=255, null=True),
        ),
    ]
