# Generated by Django 2.1.7 on 2019-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0031_auto_20190516_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Color group',
                'verbose_name_plural': 'Color groups',
                'proxy': True,
                'indexes': [],
            },
            bases=('elsecmh.colorgroup',),
        ),
        migrations.CreateModel(
            name='ColorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'proxy': True,
                'indexes': [],
            },
            bases=('elsecmh.color',),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_space',
            field=models.CharField(choices=[('RGB', 'RGB'), ('sRGB', 'sRGB'), ('RGB', 'RGB'), ('HSV', 'HSV'), ('HSL', 'HSL')], max_length=64),
        ),
    ]
