# Generated by Django 2.1.7 on 2019-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsecmh', '0032_auto_20190523_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_space',
            field=models.CharField(choices=[('RGB', 'RGB'), ('sRGB', 'sRGB'), ('CMYK', 'CMYK'), ('HSV', 'HSV'), ('HSL', 'HSL')], max_length=64),
        ),
    ]
